CREATE TABLE PRODUTORA (
CNPJ NUMBER (14,0) NOT NULL,
NOME VARCHAR (30),
PRIMARY KEY (CNPJ)
);

CREATE TABLE VIDEO (
CODIGOVIDEO NUMBER(20,0) NOT NULL,
NOME VARCHAR (30),
FORMATO VARCHAR (6),
DURACAO NUMBER (12,0),
FINALIDADE VARCHAR (20),
CANAL VARCHAR (30),
PLATAFORMA VARCHAR (30),
DIRETOR VARCHAR (30),
ROTEIRISTA VARCHAR (30),
TAMANHO VARCHAR(20),
DURACAOMAX NUMBER(3,0) DEFAULT 60,
INTENCAO VARCHAR (30),
MEIODISTRIBUICAO VARCHAR (30),
DURACAOMIN NUMBER(3, 0) DEFAULT 61,
PRIMARY KEY (CODIGOVIDEO)
);

CREATE TABLE NACIONALIDADE (
CODIGO NUMBER(10,0) NOT NULL,
ORIGEM VARCHAR(20),
IDIOMA VARCHAR(20),
MOEDA VARCHAR(10),
ESTADO VARCHAR(20),
PRIMARY KEY (CODIGO)
);

CREATE TABLE CLIENTE (
NOME VARCHAR(30) NOT NULL,
DINHEIRO NUMBER(20,2),
TIPO VARCHAR(15),
CNPJ NUMBER(14,0) UNIQUE,
CPF NUMBER(11,0) UNIQUE,
CODIGONACIONALIDADE NUMBER(10,0),
PRIMARY KEY (NOME),
FOREIGN KEY (CODIGONACIONALIDADE) REFERENCES NACIONALIDADE(CODIGO)
);

CREATE TABLE SOLICITACAO (
CONTRATO NUMBER(20,0) NOT NULL,
VALOR NUMBER(20,2),
NOMEVIDEO VARCHAR(30),
DATAINICIO VARCHAR(10),
DATAFINAL VARCHAR(10),
NOMECLIENTE VARCHAR(30),
CNPJPRODUTORA NUMBER(14, 0),
PRIMARY KEY (CONTRATO),
FOREIGN KEY (NOMECLIENTE) REFERENCES CLIENTE(NOME),
FOREIGN KEY (CNPJPRODUTORA) REFERENCES PRODUTORA(CNPJ)
);

CREATE TABLE ESTUDIO (
NOME VARCHAR(30) NOT NULL,
LOCALIZACAO VARCHAR (30),
CNPJPRODUTORA NUMBER(14, 0),
PRIMARY KEY (NOME),
FOREIGN KEY (CNPJPRODUTORA) REFERENCES PRODUTORA(CNPJ)
);

CREATE TABLE EDITOR (
NOME VARCHAR(30) NOT NULL,
IDADE NUMBER(2,0),
PORTFOLIO VARCHAR(50),
NOMEESTUDIO VARCHAR(30),
PRIMARY KEY (NOME),
FOREIGN KEY (NOMEESTUDIO) REFERENCES ESTUDIO(NOME)
);

CREATE TABLE EQUIPAMENTO (
NUMSERIE NUMBER(20,0) NOT NULL,
TIPOEQUIPAMENTO VARCHAR(30),
MARCA VARCHAR(30),
NOMEESTUDIO VARCHAR(30),
PRIMARY KEY (NUMSERIE),
FOREIGN KEY (NOMEESTUDIO) REFERENCES ESTUDIO(NOME)
);

CREATE TABLE SOFTWARE (
NOME VARCHAR(30) NOT NULL,
DESENVOLVEDORA VARCHAR(30),
ISPAGO VARCHAR(1),
FUNCAO VARCHAR(20),
TIPOCORTE VARCHAR(20),
BRILHO NUMBER(3,0),
CONTRASTE NUMBER(3,0),
MIXAGEM VARCHAR(20),
VOLUME NUMBER(3,0),
EFEITO VARCHAR(20),
POSPROCESSAMENTO VARCHAR(20),
NOMESOFTWARE VARCHAR(30),
PRIMARY KEY (NOME),
FOREIGN KEY (NOMESOFTWARE) REFERENCES SOFTWARE(NOME)
);

CREATE TABLE VIDEOEDITOR (
CODIGOVIDEO NUMBER(20,0) NOT NULL,
NOMEEDITOR VARCHAR (30) NOT NULL,
PRIMARY KEY (CODIGOVIDEO, NOMEEDITOR),
FOREIGN KEY (CODIGOVIDEO) REFERENCES VIDEO(CODIGOVIDEO),
FOREIGN KEY (NOMEEDITOR) REFERENCES EDITOR(NOME)
);

CREATE TABLE EDITOREQUIPAMENTO (
NOMEEDITOR VARCHAR (30) NOT NULL,
NUMSERIEEQUIPAMENTO NUMBER(20,0) NOT NULL,
PRIMARY KEY (NOMEEDITOR, NUMSERIEEQUIPAMENTO),
FOREIGN KEY (NOMEEDITOR) REFERENCES EDITOR(NOME),
FOREIGN KEY (NUMSERIEEQUIPAMENTO) REFERENCES EQUIPAMENTO(NUMSERIE)
);

CREATE TABLE EQUIPAMENTOSOFTWARE (
NUMSERIEEQUIPAMENTO NUMBER(20,0) NOT NULL,
NOMESOFTWARE VARCHAR(30) NOT NULL,
PRIMARY KEY (NUMSERIEEQUIPAMENTO, NOMESOFTWARE),
FOREIGN KEY (NUMSERIEEQUIPAMENTO) REFERENCES EQUIPAMENTO(NUMSERIE),
FOREIGN KEY (NOMESOFTWARE) REFERENCES SOFTWARE(NOME)
);