CREATE TABLE PRODUTORA (
CNPJ DECIMAL (14,0) NOT NULL,
NOME VARCHAR (30),
PRIMARY KEY (CNPJ)
);

CREATE TABLE VIDEO (
CODIGOVIDEO DECIMAL(20,0) NOT NULL,
NOME VARCHAR (30),
FORMATO VARCHAR (6),
DURACAO DECIMAL (12,0),
FINALIDADE VARCHAR (20),
CANAL VARCHAR (30),
PLATAFORMA VARCHAR (30),
DIRETOR VARCHAR (30),
ROTEIRISTA VARCHAR (30),
TAMANHO VARCHAR(20),
DURACAOMAX DECIMAL(3,0) DEFAULT 60,
INTENCAO VARCHAR (30),
MEIODISTRIBUICAO VARCHAR (30),
DURACAOMIN DECIMAL(3, 0) DEFAULT 61,
PRIMARY KEY (CODIGOVIDEO)
);

CREATE TABLE NACIONALIDADE (
CODIGO DECIMAL(10,0) NOT NULL,
ORIGEM VARCHAR(20),
IDIOMA VARCHAR(20),
MOEDA ENUM ('DOLAR_US', 'EURO', 'YEN', 'PESO_AR'),
ESTADO VARCHAR(20),
PRIMARY KEY (CODIGO)
);

CREATE TABLE CLIENTE (
NOME VARCHAR(30) NOT NULL,
DINHEIRO DECIMAL(20,2),
TIPO VARCHAR(15),
CNPJ DECIMAL(14,0) UNIQUE,
CPF DECIMAL(11,0) UNIQUE,
CODIGONACIONALIDADE DECIMAL(10,0),
PRIMARY KEY (NOME),
FOREIGN KEY (CODIGONACIONALIDADE) REFERENCES NACIONALIDADE(CODIGO)
);

CREATE TABLE SOLICITACAO (
CONTRATO DECIMAL(20,0) NOT NULL,
VALOR DECIMAL(20,2),
NOMEVIDEO VARCHAR(30),
DATAINICIO VARCHAR(10),
DATAFINAL VARCHAR(10),
NOMECLIENTE VARCHAR(30),
CNPJPRODUTORA DECIMAL(14, 0),
PRIMARY KEY (CONTRATO),
FOREIGN KEY (NOMECLIENTE) REFERENCES CLIENTE(NOME),
FOREIGN KEY (CNPJPRODUTORA) REFERENCES PRODUTORA(CNPJ)
);

CREATE TABLE ESTUDIO (
NOME VARCHAR(30) NOT NULL,
LOCALIZACAO VARCHAR (30),
CNPJPRODUTORA DECIMAL(14, 0),
PRIMARY KEY (NOME),
FOREIGN KEY (CNPJPRODUTORA) REFERENCES PRODUTORA(CNPJ)
);

CREATE TABLE EDITOR (
NOME VARCHAR(30) NOT NULL,
IDADE DECIMAL(2,0),
PORTFOLIO VARCHAR(50),
NOMEESTUDIO VARCHAR(30),
PRIMARY KEY (NOME),
FOREIGN KEY (NOMEESTUDIO) REFERENCES ESTUDIO(NOME)
);

CREATE TABLE EQUIPAMENTO (
NUMSERIE DECIMAL(20,0) NOT NULL,
TIPOEQUIPAMENTO VARCHAR(30),
MARCA VARCHAR(30),
NOMEESTUDIO VARCHAR(30),
PRIMARY KEY (NUMSERIE),
FOREIGN KEY (NOMEESTUDIO) REFERENCES ESTUDIO(NOME)
);

CREATE TABLE SOFTWARE (
NOME VARCHAR(30) NOT NULL,
DESENVOLVEDORA VARCHAR(30),
ISPAGO VARCHAR(1),
FUNCAO VARCHAR(20),
TIPOCORTE ENUM('LIVRE', 'RETANGULAR', 'CORRIGIR', 'ROTACIONAR'),
BRILHO DECIMAL(3,0),
CONTRASTE DECIMAL(3,0),
MIXAGEM ENUM('EQUALIZACAO', 'REDUZIR_RUIDO', 'CROSSFADE', 'MODULACAO'),
VOLUME DECIMAL(3,0),
EFEITO ENUM('CONVOLUCAO', 'EXTRAIR', 'DESFOQUE', 'NITIDEZ'),
POSPROCESSAMENTO ENUM ('CORRECAO_CORES', 'CANAL_3D', 'DISTORCER', 'RUIDO_GRANULACAO'),
NOMESOFTWARE VARCHAR(30),
PRIMARY KEY (NOME),
FOREIGN KEY (NOMESOFTWARE) REFERENCES SOFTWARE(NOME)
);

CREATE TABLE VIDEOEDITOR (
CODIGOVIDEO DECIMAL(20,0) NOT NULL,
NOMEEDITOR VARCHAR (30) NOT NULL,
PRIMARY KEY (CODIGOVIDEO, NOMEEDITOR),
FOREIGN KEY (CODIGOVIDEO) REFERENCES VIDEO(CODIGOVIDEO),
FOREIGN KEY (NOMEEDITOR) REFERENCES EDITOR(NOME)
);

CREATE TABLE EDITOREQUIPAMENTO (
NOMEEDITOR VARCHAR (30) NOT NULL,
NUMSERIEEQUIPAMENTO DECIMAL(20,0) NOT NULL,
PRIMARY KEY (NOMEEDITOR, NUMSERIEEQUIPAMENTO),
FOREIGN KEY (NOMEEDITOR) REFERENCES EDITOR(NOME),
FOREIGN KEY (NUMSERIEEQUIPAMENTO) REFERENCES EQUIPAMENTO(NUMSERIE)
);

CREATE TABLE EQUIPAMENTOSOFTWARE (
NUMSERIEEQUIPAMENTO DECIMAL(20,0) NOT NULL,
NOMESOFTWARE VARCHAR(30) NOT NULL,
PRIMARY KEY (NUMSERIEEQUIPAMENTO, NOMESOFTWARE),
FOREIGN KEY (NUMSERIEEQUIPAMENTO) REFERENCES EQUIPAMENTO(NUMSERIE),
FOREIGN KEY (NOMESOFTWARE) REFERENCES SOFTWARE(NOME)
);





