INSERT INTO PRODUTORA(CNPJ, NOME)
VALUES(12345678901234, 'Produtora A');

INSERT INTO VIDEO(CODIGOVIDEO, NOME, FORMATO, DURACAO, FINALIDADE, DIRETOR, ROTEIRISTA, TAMANHO)
VALUES(12345, 'Video A', 'MP4', 120, 'Cinematográfico', 'José', 'Luiza', 'LongaMetragem');

INSERT INTO NACIONALIDADE (CODIGO, ORIGEM, ESTADO)
VALUES (1, 'Nacional', 'São Paulo');

INSERT INTO CLIENTE(NOME, DINHEIRO, TIPO, CPF, CODIGONACIONALIDADE)
VALUES ('João', 2000, 'PessoaFisica', 12345678901, 1);

INSERT INTO SOLICITACAO (CONTRATO, VALOR, NOMEVIDEO, DATAINICIO, DATAFINAL, NOMECLIENTE, CNPJPRODUTORA)
VALUES (123, 1500, 'Video A', '20/10/2020', '20/11/2020', 'João', 12345678901234);

INSERT INTO ESTUDIO(NOME, LOCALIZACAO, CNPJPRODUTORA)
VALUES('Studio A', 'São Paulo', 12345678901234);

INSERT INTO EDITOR(NOME, IDADE, PORTFOLIO, NOMEESTUDIO)
VALUES('Lucas', 22, 'Porta dos Fundos', 'Studio A');

INSERT INTO EQUIPAMENTO(NUMSERIE, TIPOEQUIPAMENTO, MARCA, NOMEESTUDIO)
VALUES(123456789, 'Notebook', 'Apple', 'Studio A');

INSERT INTO SOFTWARE(NOME, DESENVOLVEDORA, ISPAGO, FUNCAO, EFEITO, POSPROCESSAMENTO)
VALUES('Premier', 'Adobe', '1', 'EdicaoVideo', 'EXTRAIR', 'DISTORCER');

INSERT INTO SOFTWARE(NOME, DESENVOLVEDORA, ISPAGO, FUNCAO, EFEITO, POSPROCESSAMENTO, NOMESOFTWARE)
VALUES('After Effects', 'Adobe', '1', 'EdicaoVideo', 'EQUALIZAÇÃO', 'RUIDO_GRANULACAO', 'Premier');

INSERT INTO VIDEOEDITOR(CODIGOVIDEO, NOMEEDITOR)
VALUES(12345, 'Lucas');

INSERT INTO EDITOREQUIPAMENTO(NOMEEDITOR, NUMSERIEEQUIPAMENTO)
VALUES('Lucas', 123456789 );

INSERT INTO EQUIPAMENTOSOFTWARE(NUMSERIEEQUIPAMENTO, NOMESOFTWARE)
VALUES(123456789, 'Premier');

COMMIT;